### PR TITLE
Add support for syndication_links plugin

### PR DESCRIPTION
**Pull request by Ruxton**
Broken out from #4.

This adds support for @dshanske's syndication_links plugin - https://github.com/dshanske/syndication-links

### CODE REVIEW

**Comment by Ruxton** [comment]
Fixes #10

**Comment by pfefferle** [comment]
I added a bit different version... what do you think?

**Comment by pfefferle** [comment]
Thanks a lot for your merge-request!

**Comment by Ruxton** [comment]
👍  looks good

**Pull request closed without merging**
