### PR TITLE
Indieweb Plugin Support

### PR DESCRIPTION
**Pull request by Ruxton**
Hey,

I'm not sure if you want to dive fully into this, but here we go.

* Adds support for https://github.com/dshanske/syndication-links
* Adds support for https://github.com/dshanske/indieweb-post-kinds

This code is currently running at https://ignite.digitalignition.net

### CODE REVIEW

**Comment by pfefferle** [comment]
sorry for the late reply but I was at vacation...

thanks a lot for your work and the merge request, I will have a look and merge it in the next few days...

**Comment by dshanske** [comment]
I think I want to try this out

**Comment by pfefferle** [comment]
I read the comment of @dshanske , that he maybe want to change something to the filter you implemented... I want to wait until he has implemented/merged the filter if @dshanske merged the feature...

**Comment by pfefferle** [comment]
@dshanske can you help me with the correct new functions? what do I have to disable and what do I have to use to get the icon and the post-kind-type with link?

**Comment by dshanske** [comment]
https://github.com/dshanske/indieweb-post-kinds/blob/master/includes/class-kind-taxonomy.php#L690 - The function for calling for the icon or the text.

To disable the option setting to let the user add or remove the icon and/or disable the automatic icon - https://github.com/dshanske/indieweb-post-kinds/blob/master/includes/class-kind-taxonomy.php#L681

To actually get the icon based on the kind slug - https://github.com/dshanske/indieweb-post-kinds/blob/master/includes/class-kind-taxonomy.php#L704

To get a URL to the kind archive: https://github.com/dshanske/indieweb-post-kinds/blob/master/includes/kind-functions.php#L50

To get the translated string name of the Kind: https://github.com/dshanske/indieweb-post-kinds/blob/master/includes/kind-functions.php#L40

To get the kind for a given post or current post: https://github.com/dshanske/indieweb-post-kinds/blob/master/includes/kind-functions.php#L70

**Comment by Ruxton** [comment]
I'm going to close this in favour of some new PR's that break each piece out.  First up #12

**Pull request closed without merging**
